[package]
name = "an_codes"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
itertools = "0.14.0"
serde = "1.0.217"
an_macros = { path = "./an_macros" }
num-traits = "0.2.19"
num = "0.4.3"
clap = { version = "4.4.18", features = ["derive"] }
num_cpus = "1.16.0"
